#include "models.hpp"

#include <bit>
#include <cmath>
#include <span>

// Measured model frequencies (docs/ROADMAP.md M3). Generated by
// tools/train_tables from a corpus of real scroll volumes; see the file header.
#include "tables_v2.inc"


namespace gpudct::detail {
namespace {

// Prior over a byte of a significance mask: each set bit costs a factor p.
// Sparse bands get a small p, dense bands a larger one.
std::vector<std::uint32_t> byte_prior(double p) {
  std::vector<std::uint32_t> c(256);
  for (int b = 0; b < 256; ++b) {
    const int pop = std::popcount(static_cast<unsigned>(b));
    const double w = 1e7 * std::pow(p, pop);
    c[static_cast<std::size_t>(b)] = static_cast<std::uint32_t>(std::max(1.0, w));
  }
  return c;
}

// Geometric prior over the level alphabet, with a modest tail for the escape.
std::vector<std::uint32_t> level_prior(double decay, double escape_weight) {
  std::vector<std::uint32_t> c(kLevelSyms);
  for (std::uint32_t k = 0; k < kLevelEscape; ++k)
    c[k] = static_cast<std::uint32_t>(std::max(1.0, 1e7 * std::pow(decay, k)));
  c[kLevelEscape] = static_cast<std::uint32_t>(std::max(1.0, 1e7 * escape_weight));
  return c;
}

}  // namespace

ModelSet ModelSet::defaults(std::uint32_t version) {
  // Version 2 is the shipped default: frequencies measured on real scroll data.
  // Version 1 is the original analytic prior, kept because archives written
  // against it must keep decoding -- a table is part of the format, not a
  // tuning knob.
  // The size guard is not paranoia: the generated table is a separate artifact
  // from the model layout, and adding a context without regenerating it would
  // otherwise index past the end. Falling back to the analytic prior keeps the
  // build bootstrappable -- the trainer itself runs against version 1.
  if (version >= 2 && std::size(kTrainedTables) == ModelIndex::total) {
    ModelSet s;
    s.models_.resize(ModelIndex::total);
    for (std::uint16_t i = 0; i < ModelIndex::total; ++i)
      s.models_[i] = Model::from_freqs(kTrainedTables[i]);
    // Model 0 is never trained. "Bypass" means unmodelled by definition: the
    // decoder codes those bits through bypass_model() directly, so a trained
    // table here would desync encoder and decoder. It matched by coincidence
    // while the analytic prior was also exactly 50/50.
    s.models_[ModelIndex::bypass] = bypass_model();
    return s;
  }

  ModelSet s;
  s.models_.resize(ModelIndex::total);

  // Never anything but 50/50 -- see the note in the version-2 branch above.
  s.models_[ModelIndex::bypass] = bypass_model();

  {
    // Exponent is 0 for every chunk unless relative scaling is enabled, so the
    // prior is sharply peaked there and costs almost nothing in the common case.
    std::vector<std::uint32_t> c(256, 1);
    c[0] = 1000000;
    s.models_[ModelIndex::exponent] = Model::from_counts(c);
  }

  {
    // Most chunks of a scroll volume are air and code to nothing at all.
    const std::uint32_t c[2] = {6, 4};
    s.models_[ModelIndex::chunk_nonzero] = Model::from_counts(c);
  }

  // L1: which sub-blocks are significant. Later byte positions cover higher
  // frequencies and are much sparser -- the decay is geometric, not linear,
  // because coefficient significance falls off geometrically with frequency.
  // Getting this wrong is expensive in a way that is easy to miss: seven
  // all-zero mask bytes at a too-dense prior cost ~4 bits each instead of a
  // fraction of a bit, which is most of the cost of a DC-only chunk.
  for (int j = 0; j < 8; ++j) {
    const double base = 0.30 * std::pow(0.45, j);  // 0.30 down to ~0.001
    for (int c = 0; c < kMaskCtxCount; ++c)
      s.models_[ModelIndex::l1(j, c)] =
          Model::from_counts(byte_prior(base * (1.0 + 0.8 * c)));
  }

  // L2: which coefficients within a significant sub-block are nonzero.
  {
    const double band_p[kNumBands] = {0.50, 0.20, 0.08, 0.03};
    for (int b = 0; b < kNumBands; ++b)
      for (int c = 0; c < kMaskCtxCount; ++c)
        s.models_[ModelIndex::l2(b, c)] =
            Model::from_counts(byte_prior(band_p[b] * (1.0 + 0.6 * c)));
  }

  // Levels: magnitudes decay faster at high frequency, and a large neighbour
  // makes a large magnitude more likely.
  {
    const double band_decay[kNumBands] = {0.62, 0.52, 0.44, 0.36};
    const double ctx_boost[kLevelCtxCount] = {1.0, 1.1, 1.2, 1.3, 1.42, 1.55};
    for (int b = 0; b < kNumBands; ++b)
      for (int c = 0; c < kLevelCtxCount; ++c) {
        const double d = std::min(0.9, band_decay[b] * ctx_boost[c]);
        s.models_[ModelIndex::level(b, c)] = Model::from_counts(level_prior(d, 0.002));
      }
  }

  {
    // Bit-length priors. DC magnitudes cluster around a scale set by the
    // quantizer; AC escapes are rarer and smaller.
    std::vector<std::uint32_t> dc(kLenSyms, 1), esc(kLenSyms, 1);
    for (std::uint32_t k = 1; k < kLenSyms; ++k) {
      const double dd = std::exp(-0.5 * (static_cast<double>(k) - 10.0) *
                                 (static_cast<double>(k) - 10.0) / 9.0);
      dc[k] = static_cast<std::uint32_t>(std::max(1.0, 1e6 * dd));
      esc[k] = static_cast<std::uint32_t>(std::max(1.0, 1e6 * std::pow(0.45, k)));
    }
    s.models_[ModelIndex::dc_len] = Model::from_counts(dc);
    s.models_[ModelIndex::esc_len] = Model::from_counts(esc);
  }

  {
    // Corrections are rare by construction -- they exist to clip the tail of the
    // error distribution -- and when present they are small, because a large
    // residual would have been caught by the quantizer.
    const std::uint32_t flag[2] = {9, 1};
    s.models_[ModelIndex::corr_flag] = Model::from_counts(flag);
    s.models_[ModelIndex::corr_mag] = Model::from_counts(level_prior(0.35, 0.001));
  }

  return s;
}

ModelSet ModelSet::from_counts(std::span<const std::vector<std::uint32_t>> counts) {
  ModelSet s;
  s.models_.resize(ModelIndex::total);
  const ModelSet fallback = defaults();
  for (std::uint16_t i = 0; i < ModelIndex::total; ++i) {
    if (i < counts.size() && !counts[i].empty()) {
      std::uint64_t total = 0;
      for (std::uint32_t c : counts[i]) total += c;
      // A model the corpus never exercised keeps its analytic prior rather than
      // collapsing to uniform, which would be strictly worse.
      if (total > 0) {
        s.models_[i] = Model::from_counts(counts[i]);
        continue;
      }
    }
    s.models_[i] = fallback[i];
  }
  s.models_[ModelIndex::bypass] = bypass_model();
  return s;
}

void ModelSet::serialize(std::vector<std::uint8_t>& out) const {
  out.push_back(static_cast<std::uint8_t>(models_.size() & 0xff));
  out.push_back(static_cast<std::uint8_t>((models_.size() >> 8) & 0xff));
  for (const Model& m : models_) m.serialize(out);
}

bool ModelSet::deserialize(std::span<const std::uint8_t> in, std::size_t& pos, ModelSet& out) {
  if (pos + 2 > in.size()) return false;
  const std::size_t n =
      static_cast<std::size_t>(in[pos]) | (static_cast<std::size_t>(in[pos + 1]) << 8);
  pos += 2;
  if (n != ModelIndex::total) return false;
  out.models_.assign(n, Model{});
  for (std::size_t i = 0; i < n; ++i)
    if (!Model::deserialize(in, pos, out.models_[i])) return false;
  return true;
}

// --------------------------------------------------------------------------

CountCollector::CountCollector() {
  counts.resize(ModelIndex::total);
  const ModelSet d = ModelSet::defaults();
  for (std::uint16_t i = 0; i < ModelIndex::total; ++i) counts[i].assign(d[i].nsym(), 0);
}

void CountCollector::add(const Sym& s) {
  if (s.model < counts.size() && s.value < counts[s.model].size()) ++counts[s.model][s.value];
}

void CountCollector::merge(const CountCollector& other) {
  for (std::size_t i = 0; i < counts.size() && i < other.counts.size(); ++i)
    for (std::size_t j = 0; j < counts[i].size() && j < other.counts[i].size(); ++j)
      counts[i][j] += other.counts[i][j];
}

}  // namespace gpudct::detail
